// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xztmcayunzpeborushwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dG1jYXl1bnpwZWJvcnVzaHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTg0NTQsImV4cCI6MjA2NjUzNDQ1NH0.ch4xIc6INWbOXp9uWAvnp5BvnTKw_GnHrwYQ6B4IhJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);